cc_test(
    name = "test_app",
    srcs = ["test_app.cpp"],
    deps = [
        "",
        "//src/main:bazel_cpp_app_template",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)
